### ISSUE TITLE
exmagick 0.5.0 doesn't compile on Apple Silicon (M1) with arm64 graphicsmagick

### ISSUE THREAD

**Issue by hugooliveirad** [Xerpa/exmagick#16]
I wasn't able to debug in depth, but I could not get `mix deps.compile exmagick` to work on Apple Silicon (M1, 2020) using arm64 `graphicsmagick`.

I kept getting this error:

```
glibtool: link: clang -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o /Users/hugo/workspace/seatscouts/gamma/_build/dev/.libs/libexmagick.0.dylib  /Users/hugo/workspace/seatscouts/gamma/_build/dev/lib/c/.libs/exmagick.o   -L/opt/homebrew/Cellar/graphicsmagick/1.3.36/lib -L/opt/home
brew/opt/freetype/lib -L/usr/local/lib /opt/homebrew/Cellar/graphicsmagick/1.3.36/lib/libGraphicsMagick.dylib -llcms2 -lfreetype -lbz2 -lz -lltdl -lm -lpthread    -install_name  /opt/homebrew/opt/freetype/lib/libexmagick.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-sin
gle_module
ld: library not found for -llcms2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/hugo/workspace/seatscouts/gamma/_build/dev/libexmagick.la] Error 1
==> exmagick
could not compile dependency :exmagick, "mix compile" failed. You can recompile this dependency with "mix deps.compile exmagick", update it with "mix deps.update exmagick" or clean it with "mix deps.clean exmagick"
** (MatchError) no match of right hand side value: {%IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}, 2}
    /Users/hugo/workspace/seatscouts/gamma/deps/exmagick/mix.exs:13: Mix.Tasks.Compile.ExMagick.runcmd/2
    /Users/hugo/workspace/seatscouts/gamma/deps/exmagick/mix.exs:8: Mix.Tasks.Compile.ExMagick.run/1
    (mix 1.11.3) lib/mix/task.ex:394: Mix.Task.run_task/3
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:90: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:70: Mix.Tasks.Compile.All.compile/4
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:57: Mix.Tasks.Compile.All.with_logger_app/2
    (mix 1.11.3) lib/mix/tasks/compile.all.ex:35: Mix.Tasks.Compile.All.run/1
```

The only way I got this library to compile was installing a Rosetta 2 Homebrew and running `arch -x86_64 /usr/local/bin/brew install graphicsmagick`.

The installed `graphicmagick` was:

```
graphicsmagick: stable 1.3.36 (bottled), HEAD
Image processing tools collection
http://www.graphicsmagick.org/
/usr/local/Cellar/graphicsmagick/1.3.36 (494 files, 15.9MB) *
  Poured from bottle on 2021-06-29 at 17:12:06
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/graphicsmagick.rb
==> Dependencies
Build: pkg-config ✘
Required: freetype ✔, jasper ✔, jpeg ✔, libpng ✔, libtiff ✔, libtool ✔, little-cms2 ✔, webp ✔
==> Options
--HEAD
        Install HEAD version
==> Analytics
install: 6,606 (30 days), 22,585 (90 days), 106,490 (365 days)
install-on-request: 4,220 (30 days), 14,320 (90 days), 62,309 (365 days)
build-error: 0 (30 days)
```

This could be an issue with `graphicsmagick` dependency or the way `exmagick` is trying to `make` it.

I'm on macOS 11.4

**Comment by thalesmg** [comment]
According to the error message, it seems to be a missing dependency.

Have you tried to install `lcms2`?

```sh
brew install little-cms2
```

**Comment by dabaer** [comment]
I have the same issue, however lcms2 is already installed.
 `Warning: little-cms2 2.12 is already installed and up-to-date.`

**Comment by dabaer** [comment]
@hugobdev so I did some digging and found you need to set your compiler environment variables to include homebrew's M1 paths which are different than the default.

```
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```

Then you should be able to compile your project with only arm libraries.

**Comment by ederchristian** [comment]
```
export CPATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```

It worked. Thanks, @dabaer!

**Comment by hugooliveirad** [comment]
Issue has a workaround, so I'm closing it. Let me know if it is worth adding to the docs.
